a = input("enter number a: ")
b = input("enter number b: ")
a = int(a)
b = int(b)
print("Addition : ",a + b)
print("Substraction : ",a - b)
print("Multiplication : ",a * b)
print("Division : ",a / b)